app:
  test: "something"
  baseUrlGitHub: "https://api.github.com"
  baseUrlStackOverflow: "https://api.stackexchange.com"
  scheduler:
    interval: 10000

springdoc:
  swagger-ui:
    path: "/swagger-ui"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:migrations/master.xml